### ISSUE TITLE
use structopt for command line argument setup

### ISSUE THREAD

**Issue by philipcraig** [jbcoe/mylang#40]
@jbcoe could you please give me any suggestions of what command lines you would like to support that result in what things?

e.g. `mylang --show-errors` and what it does, or `mylang --lex-only` or `my-ang --parse-only` or whatever?

**Comment by jbcoe** [comment]
Maybe `mylang` `mylang tokens` `mylang parse` followed by (a) filename(s).

**Comment by philipcraig** [comment]
done in #70
