### ISSUE TITLE
Code coverage is not giving file info for me

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/mylang#96]
The following link is not giving file info as I'd like:

https://codecov.io/gh/jbcoe/mylang/src/main/src/parser.rs

Linked from https://codecov.io/gh/jbcoe/mylang/tree/main/src

Might be an intermittent problem but was reproducible.

**Comment by philipcraig** [comment]
You've not said what info you'd like it to give, and what you got instead.

Might it be a browser-cache issue?

**Comment by jbcoe** [comment]
Whatever was wrong seems fine now. Thanks for taking a look. 

Closing issue as I cannot reproduce the problem.
